# Generated by Django 4.0.1 on 2022-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0002_alter_blogs_plant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Plant_Type',
            field=models.CharField(choices=[('Outdoor Plant', 'Outdoor Plant'), ('Indoor Plant', 'Indoor Plant'), ('Low Mantenance Plant', 'Low Mantenance Plant'), ('Harbal Plant', 'Harbal Plant'), ('Air Purifier Plant', 'Air Purifier Plant'), ('Flowering Plant', 'Flowering Plant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Plant_Type',
            field=models.CharField(choices=[('Outdoor Plant', 'Outdoor Plant'), ('Indoor Plant', 'Indoor Plant'), ('Low Mantenance Plant', 'Low Mantenance Plant'), ('Harbal Plant', 'Harbal Plant'), ('Air Purifier Plant', 'Air Purifier Plant'), ('Flowering Plant', 'Flowering Plant')], max_length=50),
        ),
    ]
