# Generated by Django 4.0.1 on 2022-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0003_alter_blogs_plant_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='Evolution',
            new_name='Common_Problems',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='Intro',
            new_name='Plant_Essentials',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='Medicine',
            new_name='Style_and_Décor',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Plant_Type',
            field=models.CharField(choices=[('Indoor Plant', 'Indoor Plant'), ('Low Mantenance Plant', 'Low Mantenance Plant'), ('Flowering Plant', 'Flowering Plant'), ('Outdoor Plant', 'Outdoor Plant'), ('Harbal Plant', 'Harbal Plant'), ('Air Purifier Plant', 'Air Purifier Plant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Plant_Type',
            field=models.CharField(choices=[('Indoor Plant', 'Indoor Plant'), ('Low Mantenance Plant', 'Low Mantenance Plant'), ('Flowering Plant', 'Flowering Plant'), ('Outdoor Plant', 'Outdoor Plant'), ('Harbal Plant', 'Harbal Plant'), ('Air Purifier Plant', 'Air Purifier Plant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], max_length=50),
        ),
    ]
