# Generated by Django 4.0.1 on 2022-05-26 14:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursery', '0004_rename_evolution_blogs_common_problems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Common_Problems',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Plant_Essentials',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Plant_Type',
            field=models.CharField(choices=[('Flowering Plant', 'Flowering Plant'), ('Outdoor Plant', 'Outdoor Plant'), ('Low Mantenance Plant', 'Low Mantenance Plant'), ('Indoor Plant', 'Indoor Plant'), ('Harbal Plant', 'Harbal Plant'), ('Air Purifier Plant', 'Air Purifier Plant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Style_and_Décor',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Plant_Type',
            field=models.CharField(choices=[('Flowering Plant', 'Flowering Plant'), ('Outdoor Plant', 'Outdoor Plant'), ('Low Mantenance Plant', 'Low Mantenance Plant'), ('Indoor Plant', 'Indoor Plant'), ('Harbal Plant', 'Harbal Plant'), ('Air Purifier Plant', 'Air Purifier Plant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
    ]
